JournalWeb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('journal_web.urls', namespace='journal_web')),
]

journal_web/urls.py
from django.urls import path
from . import views

app_name = 'journal_web'

urlpatterns = [
    #Home page
    path('',views.index,name='index'),
    #Page that shows all topics
    path('topics/',views.topics,name='topics'),
    path('topics/<int:topic_id>/',views.topic,name='topic'),
    path('new_topic/',views.new_topic,name='new_topic'),
    path('new_entry/<int:topic_id>/',views.new_entry,name='new_entry'),
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),
]

users/urls.py
from django.urls import include,path
from . import views

app_name = 'users'

urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name='register')
]

apps/models/database.py
import sqlite3
from flask import Flask
class TaskManager:
    def __init__(self):
        self.__con = sqlite3.connect('tasks.db')
        self.__cur = self.__con.cursor()
        self.create_table()
        
    def __str__(self):
        return '\n'.join(str(row) for row in self.__cur.execute("SELECT * from tasks").fetchall())
    
    def __del__(self):
        self.__con.close()
    
    def create_table(self,table_name='TaskManager'):
        self.__cur.execute("""CREATE TABLE if not exists tasks(
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            description TEXT,
            deadline TEXT,
            state TEXT
        )""")
        self.__con.commit()
        
    def add_values(self,id = 0,description = '',deadline = '',state = ''):    
        self.__cur.execute("""
        INSERT INTO tasks 
        values (?,?,?,?)    
    """,(id,description,deadline,state))
        self.__con.commit()

    def remove_values(self,id_list: list):
        for id in id_list:
            self.__cur.execute("DELETE FROM tasks WHERE id = (?)",(id,))
        self.__con.commit()
        
    def update_value(self,select_id: int,field: str,new_data):
        self.__cur.execute("UPDATE tasks set (?) = (?) where id = (?)",(field,new_data,select_id,))
        self.__con.commit()
    
    def mark_completed(self,select_id: int):
        self.__cur.execute("UPDATE tasks set state = 'Done' where id = (?)",(select_id,))
        self.__con.commit()
    
    def search_tasks(self,id,description = '',deadline = '',state = ''):
        return '\n'.join(str(row) for row in self.__cur.execute("""SELECT * 
                        from tasks
                        where id = (?) 
                        and description = (?)
                        and deadline = (?)
                        and state = (?)""",(id,description,deadline,state,)
                        ).fetchall())
    
    
def test():
    # test = TaskManager()
    
    # test.add_values(1,'Testing','25-2-2025','Undone')
    # test.add_values(2,'Solving Math','27-3-2025','Done')
    # test.mark_completed(1)
    # test.update_value(1,"deadline","25-5-2025")
    #test.remove_values([1,2])
    # print(test)
    print('Hello World!')


if __name__ == '__main__':
    test()

journal_web/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.text
    
class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if(self.text == 'Vu'):
            return 'Truc'
        
        return f"{self.text[:50]}..." if len(self.text) > 50 else f'{self.text}'
        

users/models.py
from django.db import models

# Create your models here.

journal_web/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

journal_web/views.py
from django.shortcuts import render,redirect
from .models import Topic, Entry
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

def index(request):
    """The home page for Journal Web"""
    return render(request,'journal_web/index.html')

@login_required
def topics(request):
    """Show alls topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request,'journal_web/topics.html',context)   

def topic(request,topic_id):
    """Show 1 topic"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic,request)
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic,'entries': entries}
    
    return render(request,'journal_web/topic.html',context) 

@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            
            return redirect('journal_web:topics')
    context = {'form':form}
    
    return render(request,'journal_web/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('journal_web:topic',topic_id=topic_id)
    context = {'topic':topic,'form': form}
    return render(request,'journal_web/new_entry.html',context)

@login_required
def edit_entry(request,entry_id):
    entry = Entry.objects.get(entry_id)
    topic = entry.topic
    
    check_topic_owner(topic,request)
    
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('journal_web:topic',topic_id = topic.id)
        context = {'entry': entry,'topic':topic,'form':form}
        
        return render(request,'journal_web/edit_entry.html',context)

def check_topic_owner(topic,request):
    if topic.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('journal_web:index')
    
    context = {'form':form}
    return render(request,'registration/register.html',context)

journal_web/templates/journal_web/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1,
shrink-to-fit=no">
<title>Learning Log</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

</head>


<body>

    <nav class = "navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class = "navbar-brand" href = "{% url 'journal_web:index' %}">
            Journal Web</a>
        
        <button class = "navbar-toggler" type="button" data-toggle="collapse"
data-target="#navbarCollapse" aria-controls="navbarCollapse"
aria-expanded="false" aria-label="Toggle navigation">
            <span class = "navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'journal_web:topics'%}">
                        Topics</a></li>
            </ul>
        <ul class = "navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class = "nav-item">
                    <span class = "navbar-text">Hello, {{ user.user_name }}</span>
                </li>
                <li class = "nav-item">
                    <a class = "nav-link" href = "{% url 'users:logout' %}">Logout</a>
                </li>

                {% else %}
                    <li class = "nav-item">
                        <a class = "nav-link" href = "{% url 'users:register' %}"></a>
                    </li>
                    <li class = "nav-item">
                        <a class = "nav-link" href = "{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
        </ul>
    </div>
</nav>

<main role="main" class="container">
    <div class = "pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>

    <div>
        {% block content %}{% endblock content %}
    </div>
</main>

</body>

</html>

journal_web/templates/journal_web/edit_entry.html
{% extends "journal_web/base.html" %}

{% block content %}

<p><a href = "{% url 'journal_web:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>

<form action="{% url 'journal_web:edit_entry' entry.id %}" method = 'post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>






{% endblock  content %}

journal_web/templates/journal_web/index.html
{% extends "journal_web/base.html" %}

{% block page_header %}

<div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>
    <p class="lead">Make your own Learning Log, and keep a list of the
    topics you're learning about. Whenever you learn something new
    about a topic, make an entry summarizing what you've learned.</p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
    role="button">Register &raquo;</a>
</div>
    
{% endblock page_header %}

journal_web/templates/journal_web/new_entry.html
{% extends "journal_web/base.html" %}

{% block content %}
    <p><a href = "{% url 'journal_web:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>

    <form action = "{% url 'journal_web:new_entry' topic.id%}" method = 'post'>  
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>

{% endblock content %}

journal_web/templates/journal_web/new_topic.html
{% extends "journal_web/base.html" %}

{% block content %}
    <p>Add a new topic:</p>

    <form action = "{% url 'journal_web:new_topic' %}" method = 'post'>  
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>

{% endblock content %}

journal_web/templates/journal_web/topic.html
{% extends "journal_web/base.html" %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

<p>
    <a href = "{% url 'journal_web:new_entry' topic.id %}">Add a new entry</a>
</p>   

    {% for entry in entries %}
    
    <div>
        <h4 class = "card-header">
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small>
                <a href = "{% url 'journal_web:edit_entry' entry.id %}">edit entry</a>
            </small>
        </h4>
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
    </div>

    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}


{% endblock content %}

journal_web/templates/journal_web/topics.html
{% extends "journal_web/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1 class = "text-danger text-center fw-bold display-3">TOPICS</h1>
{% endblock page_header %}

{% block content %}


<ul class = "list-group mx-auto">
    {% for topic in topics %}
        <li class = "list-group-item list-group-item-light list-group-item-action text-center shadow-sm"><h4 class = "text-center">
            <a href="{% url 'journal_web:topic' topic_id=topic.id %}">{{ topic.text }}</a>  
        </h4></li>
    {% empty %}
        <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
</ul>

<div class = "mt-4 d-flex justify-content-center"><a class = "btn btn-primary d-flex justify-content-center" href = "{% url 'journal_web:new_topic' %}">Add a new topic</a></div>

{% endblock content %}